NO_BOIDS: 50
MOVEMENT_STRENGTH: 0.01
ALERT_DISTANCE: 100
FORMATION_FLYING_DISTANCE: 10000
FORMATION_FLYING_STRENGTH: 0.125
LOWER_LIM_POS: [-450.0, 300.0]
UPPER_LIM_POS: [  50.0, 600.0]
LOWER_LIM_VEL: [   0.0, -20.0]
UPPER_LIM_VEL: [  10.0,  20.0]

